### ISSUE TITLE
Problem with iOS.

### ISSUE THREAD

**Issue by irman** [MOLPay/molpay-mobile-xdk-nativescript#1]
Hi,

We've managed to integrate this on our app. It works nicely on Android, but on iOS, it doesn't load. Just blank screen.

Here's the error if it tested on simulator but I'm not sure if it's relevant:
```
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
            [x86_64] libnetcore-856.30.16
        0   libsystem_network.dylib             0x00000001126b4666 __nw_create_backtrace_string + 123
        1   libnetwork.dylib                    0x0000000112992006 nw_socket_add_input_handler + 3164
        2   libnetwork.dylib                    0x000000011296f555 nw_endpoint_flow_attach_protocols + 3768
        3   libnetwork.dylib                    0x000000011296e572 nw_endpoint_flow_setup_socket + 563
        4   libnetwork.dylib                    0x000000011296d298 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
        5   libnetwork.dylib                    0x0000000112988ae1 nw_endpoint_handler_path_change + 1261
        6   libnetwork.dylib                    0x0000000112988510 nw_endpoint_handler_start + 570
        7   libnetwork.dylib                    0x00000001129a01f9 nw_endpoint_resolver_start_next_child + 2240
        8   libdispatch.dylib                   0x0000
[] nw_host_stats_add_src recv too small, received 24, expected 28
```

While tested on a device, no error were generated.

Kindly check.

Thanks!

**Comment by LeowWH** [comment]
Hi @irman,
Thanks for using our plugin. We cannot regenerate your problem here so maybe you have to help us try out the following and let us know the result 😀.

First can you try to create a new and clean project "tns create HelloWorld --template nativescript-template-tutorial" then follow our guild to install our plugin and try it again. We have try this with nativescript version 3.1.3 node version 7.10.0 without any problem.

Second if still cannot work can you try out our example project.

Third i have found out the below link it maybe help you to solve your problem.
https://stackoverflow.com/questions/41273773/nw-host-stats-add-src-recv-too-small-received-24-expected-28/41828707#41828707

If you still cannot solve it you can reach me on Skype or comment here so we can have a details investigation on your case.

Skype ID : lelouchliew93@hotmail.com

**Comment by irman** [comment]
Thanks for the feedback! My team will check on the suggestions and will get back to you shortly. 😄

**Comment by clewlb** [comment]
I'm closing this issue for now until someone reopen this again if the issue persists.
